import streamlit as st
import base64

with open(r"styles/main.css") as f:
    st.write(f"<style>{f.read()}</style>", unsafe_allow_html=True)

def get_base64_video(video_file):
    with open(video_file, "rb") as f:
        video_bytes = f.read()
    return base64.b64encode(video_bytes).decode()

# Get the base64 encoded video
video_base64 = get_base64_video(r"./assets/vid1.mp4")

# Embed video as background
background_video = f'''
<style>
[data-testid="stAppViewContainer"] > .main {{
    background: none;
    position: relative;
    z-index: 1;
}}

[data-testid="stAppViewContainer"]::before {{
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: -1;
    background-color: rgba(0, 0, 0, 0.5);
}}

video.background-video {{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    object-fit: cover;
    z-index: -2;
    opacity: 0.8;
}}

</style>

<video class="background-video" autoplay loop muted playsinline>
    <source src="data:video/mp4;base64,{video_base64}" type="video/mp4">
    Your browser does not support the video tag.
</video>

<style>

[data-testid="stSidebar"] > div:first-child {{
    background-image: url("https://devsnap.nyc3.digitaloceanspaces.com/devsnap.me/codepen-VjrZWv.png");
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    background-attachment: fixed;
}}

</style>
'''

# Apply the custom CSS for background video
st.markdown(background_video, unsafe_allow_html=True)
   

# Set the title of the page with a bigger font size and a different color
st.markdown("<h1 style='text-align: center; color: #F9F9F9;'>CancerForecast</h1>", unsafe_allow_html=True)

# Add a main heading with a subtitle
st.markdown("<h2 style='text-align: center; color: #F9F9F9;'>About The CancerForecast Website</h2>", unsafe_allow_html=True)
st.markdown("<p style='text-align: center; color: #F9F9F9;'>Harnessing the power of AI to explore cancer prediction</p>", unsafe_allow_html=True)

# Provide an overview with bullet points and different text styles
st.markdown("""
<div style='background-color: #F9F9F9; padding: 15px; border-radius: 8px; border: 1px solid #DDDDDD;'>
    <h3 style='color: #333333;'>Purpose of This Website</h3>
    <p style='color: #333333;'>This website is designed as a study project to predict various types of cancer using Machine Learning models. The following types of cancer can currently be predicted:</p>
    <ul style='color: #555555;'>
        <li><strong>Brain Cancer</strong></li>
        <li><strong>Acute Lymphoblastic Leukemia</strong></li>
        <li><strong>Breast Cancer</strong></li>
        <li><strong>Cervical Cancer</strong></li>
        <li><strong>Kidney Cancer</strong></li>
        <li><strong>Lung and Colon Cancer</strong></li>
    </ul>
    <p style='font-style: italic; color: #777777;'>In the future, we plan to add more cancer types to enhance the project's scope.</p>
</div>
""", unsafe_allow_html=True)

# Add a highlighted warning message
st.markdown("""
<div style='background-color: #FFF4E5; padding: 15px; border-left: 5px solid #FFB84D; margin-top: 20px;'>
    <h3 style='color: #FF0000;'>Important Note</h3>
    <p style='color: #D35400;'><strong>This website is a small project developed for study purposes only. The predictions generated by this platform are not intended for real-world medical diagnosis or treatment. Always consult a healthcare professional for medical advice.</strong></p>
</div>
""", unsafe_allow_html=True)

# Add a section about future goals with a different background
st.markdown("""
<div style='background-color: #E5F6F9; padding: 15px; border-radius: 8px; border: 1px solid #B3E0E6; margin-top: 20px;'>
    <h3 style='color: #0000FF;'>Future Goals</h3>
    <p style='color: #2980B9;'>Our goal is to continuously improve the accuracy of the models and add more cancer types as we expand the project. This is an ongoing learning experience, and we appreciate your understanding.</p>
</div>
""", unsafe_allow_html=True)

# Add a final note with centered text
st.markdown("<p style='text-align: center; font-size: 16px; color: #E6E6FA; margin-top: 30px;'>Thank you for visiting our website. We hope this project can provide some insights into the application of AI in healthcare.</p>", unsafe_allow_html=True)
